backend:
  name: git-gateway
  branch: main
  repo: https://github.com/saurabhkacholiya/docusaurus-cms-poc
  base_url: https://saurabhkacholiya.github.io/ #docusaurus-cms-poc/
  auth_endpoint: api/auth
#local_backend: true
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", required: false }
      - {
          label: "Author Title",
          name: "author_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Author URL",
          name: "author_url",
          widget: "string",
          required: false,
        }
      - {
          label: "Author Image",
          name: "author_image_url",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          timeFormat: false,
        }
      - { label: "Description", name: "description", required: false }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons:
            [
              bold,
              italic,
              code,
              link,
              heading-one,
              heading-two,
              heading-three,
              heading-four,
              heading-five,
              heading-six,
              quote,
              bulleted-list,
              numbered-list,
            ],
        }
