backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Slug", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", required: false }
      - {
          label: "Author Title",
          name: "author_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Author URL",
          name: "author_url",
          widget: "string",
          required: false,
        }
      - {
          label: "Author Image",
          name: "author_image_url",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          timeFormat: false,
        }
      - { label: "Description", name: "description", required: false }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
